### ISSUE TITLE
I don't believe the app is packaged correctly, fails to install and is called "Bixby Utils"

### ISSUE THREAD

**Issue by ChuckTheBeast** [madmagic007/True-Spotify-Shuffle#1]
It tries to install "Bixby Utils", and fails saying that the package is invalid.

**Comment by madmagic007** [comment]
It appears there is indeed an issue, it shouldn't depend on bixby utils, it's an app I made myself where one of the features can launch this service. I will look in to this. Thanks for reporting

**Comment by ChuckTheBeast** [comment]
No problem.  I tested it on a non-samsung device too and it did the same thing.  I've tried it on my S21 Ultra (Samsung OneUI 5) and my Moto G7 (stock Android 10)

**Comment by madmagic007** [comment]
Could you provide a screenshot or similar of the error you are getting?

**Comment by ChuckTheBeast** [comment]
![Screenshot_20221212_111236_Package installer](https://user-images.githubusercontent.com/104949493/207106193-734087bb-0414-4869-a390-f45f57953feb.jpg)
![Screenshot_20221212_111117_Package installer](https://user-images.githubusercontent.com/104949493/207106202-29054ab7-6f98-4af2-86d6-caf3afcbe4a0.jpg)

**Comment by madmagic007** [comment]
hmm, this is very strange. It looks like the wrong apk might have been uploaded to the releases page. I have fixed the release, can you try downloading and installing it again?

**Comment by ChuckTheBeast** [comment]
Yep, it works now.  Thanks!
